### ISSUE TITLE
KDL 2.0.0 compliance

### ISSUE THREAD

**Issue by zkat** [TheLostLambda/knus#16]
KDL 2.0.0 is about to be finally tagged (https://github.com/kdl-org/kdl/pull/434), and we're hoping the implementation community starts moving over to the new version now, which will be the "blessed" KDL going forward.

(I know this is already planned, but this is so I can put it in the [compliance tracking issue](https://github.com/kdl-org/kdl/issues/372).)

**Comment by TheLostLambda** [comment]
Currently being worked on in #21, which I'll merge into a feature branch for now!

**Comment by bew** [comment]
Hello!
I tested the `kdl-v2` branch today, hoping to build a project on it, but I noticed that the multiline strings implementation is NOT v2 compliant.

Here is a test-suite that should work but doesn't (I tested the inputs manually in https://kdl.dev/play/):
```rust
#[cfg(test)]
mod tests_knus_multiline {
    #[derive(Debug, knus::Decode, PartialEq, Eq)]
    enum Dummy {
        Content(#[knus(argument)] String)
    }

    fn assert_echo_hello(input: &'static str) {
        let res = knus::parse("test.kdl", input);
        dbg!(&res);
        let dummies: Vec<Dummy> = res.unwrap();
        assert_eq!(dummies, &[
            Dummy::Content("echo hello".into())
        ]);
    }

    #[test]
    fn oneline_string() {
        let input = r###"
            content "echo hello"
        "###;
        assert_echo_hello(input);
    }

    #[test]
    fn multiline_string() {
        let input = r###"
            content """
                echo hello
                """
        "###;
        assert_echo_hello(input);
    }

    #[test]
    fn multiline_raw_string() {
        let input = r###"
            content ##"""
                echo hello
                """##
        "###;
        assert_echo_hello(input);
    }
}
```

<details>
<summary>👉 Tests results: 1 OK - 2 FAIL</summary>

```
running 3 tests
test config::tests_knus_multiline::multiline_raw_string ... FAILED
test config::tests_knus_multiline::oneline_string ... ok
test config::tests_knus_multiline::multiline_string ... FAILED

failures:

---- config::tests_knus_multiline::multiline_raw_string stdout ----
[src/config.rs:95:9] &res = Ok(
    [
        Content(
            "\"\"\n                echo hello\n                \"\"",
        ),
    ],
)

thread 'config::tests_knus_multiline::multiline_raw_string' panicked at src/config.rs:97:9:
assertion `left == right` failed
  left: [Content("\"\"\n                echo hello\n                \"\"")]
 right: [Content("echo hello")]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- config::tests_knus_multiline::multiline_string stdout ----
[src/config.rs:95:9] &res = Err(
    Error {
        source_code: NamedSource {
            name: "test.kdl",
            source: "<redacted>",
            language: None,
        ,
        errors: [
            Conversion {
                span: Span(
                    23,
                    69,
                ),
                source: "expected one of `content`",
            },
            Conversion {
                span: Span(
                    69,
                    71,
                ),
                source: "expected one of `content`",
            },
        ],
    },
)

thread 'config::tests_knus_multiline::multiline_string' panicked at src/config.rs:96:39:
called `Result::unwrap()` on an `Err` value: Error { source_code: NamedSource { name: "test.kdl", source: "<redacted>", language: None, errors: [Diagnostic { message: "expected one of `content`", labels: "[LabeledSpan { label: Some(\"invalid value\"), span: SourceSpan { offset: SourceOffset(23), length: 46 }, primary: false }]" }
NOTE: If you're looking for the fancy error reports, install miette with the `fancy` feature, or write your own and hook it up with miette::set_hook().
, Diagnostic { message: "expected one of `content`", labels: "[LabeledSpan { label: Some(\"invalid value\"), span: SourceSpan { offset: SourceOffset(69), length: 2 }, primary: false }]" }
NOTE: If you're looking for the fancy error reports, install miette with the `fancy` feature, or write your own and hook it up with miette::set_hook().
] }


failures:
    config::tests_knus_multiline::multiline_raw_string
    config::tests_knus_multiline::multiline_string

test result: FAILED. 1 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

</details>

**Comment by kleinesfilmroellchen** [comment]
@TheLostLambda any chance we can get the current v2 featureset in a release, so that knus is at least partially v2 compliant? Especially the forbidden bare identifiers are very annoying.

**Comment by TheLostLambda** [comment]
Hi @kleinesfilmroellchen !

That's possible if needed, though it also looks like someone is in the middle of finishing things off here: https://github.com/TheLostLambda/knus/pull/33

I'm awfully busy thesis writing at the moment, but feel free to chat with the PR author and chip in, and I'll aim to get to looking at it properly as soon as I can!

**Comment by kleinesfilmroellchen** [comment]
I saw that PR, and I suppose I’ll wait for the work to finish, but if KDL 2.0 is really last in the chain and your schedule doesn’t improve, I guess there will be some waiting :)
